version: '3.7'
services:
    web:
        build: .
        restart: always
        ports:
            - '5001:8000'
        links:
            - postgres-doc:postgres-doc
        depends_on:
            - postgres-doc
    postgres-doc:
        image: postgres:12
        restart: always
        environment:
            POSTGRES_USER: 'notescoc_user'
            POSTGRES_PASSWORD: 'notescoc_password'
            POSTGRES_DB: 'notescoc_db'
        ports:
            - '5002:5432'
