"""Added creation and upgradion date for game time and real time

Revision ID: 024db9a4ac35
Revises: acf9e0fcc050
Create Date: 2022-09-22 11:55:16.153721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '024db9a4ac35'
down_revision = 'acf9e0fcc050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('game_creation_date', sa.Date(), nullable=True))
    op.add_column('notes', sa.Column('game_update_date', sa.Date(), nullable=True))
    op.add_column('notes', sa.Column('real_creation_date', sa.DateTime(), nullable=True))
    op.add_column('notes', sa.Column('real_update_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'real_update_date')
    op.drop_column('notes', 'real_creation_date')
    op.drop_column('notes', 'game_update_date')
    op.drop_column('notes', 'game_creation_date')
    # ### end Alembic commands ###
