"""Adding user registration

Revision ID: d5445f203460
Revises: dad9eebedc29
Create Date: 2022-08-07 21:54:10.158879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5445f203460'
down_revision = 'dad9eebedc29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('register_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=36), nullable=True),
    sa.Column('person_name', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['person_name'], ['persons.name'], name=op.f('fk_register_users_person_name_persons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_register_users')),
    sa.UniqueConstraint('hash', name=op.f('uq_register_users_hash'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('person_name', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['person_name'], ['persons.name'], name=op.f('fk_users_person_name_persons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('login', name=op.f('uq_users_login'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('register_users')
    # ### end Alembic commands ###
