"""Init with persons_notes table

Revision ID: dad9eebedc29
Revises: 
Create Date: 2022-08-03 21:35:20.456421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dad9eebedc29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('content', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    op.create_table('persons',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_persons'))
    )
    op.create_table('persons_notes',
    sa.Column('person_name', sa.String(length=80), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('fk_persons_notes_note_id_notes')),
    sa.ForeignKeyConstraint(['person_name'], ['persons.name'], name=op.f('fk_persons_notes_person_name_persons')),
    sa.PrimaryKeyConstraint('person_name', 'note_id', name=op.f('pk_persons_notes'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persons_notes')
    op.drop_table('persons')
    op.drop_table('notes')
    # ### end Alembic commands ###
