apiVersion: v1
kind: Service
metadata:
  name: notescoc-service
  labels:
    app: notescoc
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30004
  selector:
    app: notescoc
    type: app
