apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    tier: db
    app: notescoc
spec:
  selector:
    matchLabels:
      app: notescoc
      type: db
  replicas: 1
  template:
    metadata:
      name: postgres-app
      labels:
        app: notescoc
        type: db
    spec:
      containers:
        - name: postgres
          image: postgres
          envFrom:
            - configMapRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim

