apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  labels:
    app: notescoc
    type: local
    tier: db
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/postgresql"