apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: notescoc
    tier: db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: notescoc
    type: db
