"""Setiings model added to user

Revision ID: 6c1f5dc1d3fc
Revises: 525ba4ea2b19
Create Date: 2022-10-08 22:12:08.394206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c1f5dc1d3fc'
down_revision = '525ba4ea2b19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('today_game_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings'))
    )
    op.add_column('users', sa.Column('setting_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_users_setting_id_settings'), 'users', 'settings', ['setting_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_setting_id_settings'), 'users', type_='foreignkey')
    op.drop_column('users', 'setting_id')
    op.drop_table('settings')
    # ### end Alembic commands ###
