"""Added subjects of notes and categories of subjects

Revision ID: acf9e0fcc050
Revises: c93f13549a93
Create Date: 2022-08-28 21:50:16.097206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf9e0fcc050'
down_revision = 'c93f13549a93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_categories',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_subject_categories'))
    )
    op.create_table('subjects',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_subjects'))
    )
    op.create_table('notes_subjects',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('fk_notes_subjects_note_id_notes')),
    sa.ForeignKeyConstraint(['subject_name'], ['subjects.name'], name=op.f('fk_notes_subjects_subject_name_subjects')),
    sa.PrimaryKeyConstraint('note_id', 'subject_name', name=op.f('pk_notes_subjects'))
    )
    op.create_table('subjects_categories',
    sa.Column('subject_name', sa.String(length=80), nullable=False),
    sa.Column('subject_categories_name', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['subject_categories_name'], ['subject_categories.name'], name=op.f('fk_subjects_categories_subject_categories_name_subject_categories')),
    sa.ForeignKeyConstraint(['subject_name'], ['subjects.name'], name=op.f('fk_subjects_categories_subject_name_subjects')),
    sa.PrimaryKeyConstraint('subject_name', 'subject_categories_name', name=op.f('pk_subjects_categories'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subjects_categories')
    op.drop_table('notes_subjects')
    op.drop_table('subjects')
    op.drop_table('subject_categories')
    # ### end Alembic commands ###
